name: infrastructureDeploy

on: [push]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    
    env:
      YC_TOKEN: ${{ secrets.YC_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set ssh-public key in cloud_config file
        run: echo "      - ${{ secrets.SSH_PUB_KEY }}" >> ./terraform/cloud_config.yaml

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.5"

      - name: Terraform Init
        working-directory: ./terraform
        id: init
        run: |
          terraform init \
            --backend-config "access_key=${{ secrets.BACKEND_CRED_ACCESS_KEY }}" \
            --backend-config "secret_key=${{ secrets.BACKEND_CRED_SECRET_KEY }}"

      - name: Terraform Plan
        working-directory: ./terraform
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform apply
        working-directory: ./terraform
        id: apply
        run: terraform apply -auto-approve