name: infrastructureDeploy

on: [push]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set ssh-public key in cloud_config file
        run: echo "      - ${{ secrets.SSH_PUB_KEY }}" >> ./terraform/cloud_config.yaml

      - name: Set backend credentials
        run: echo "${{ secrets.BACKEND_CRED }}" > ./terraform/backend.cred

      - name: show cloud_config
        run: cat ./terraform/cloud_config.yaml

      - name: show backend credentials
        run: cat ./terraform/backend.cred